name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.12.0
    steps:
    - name: Clone the repo
      uses: actions/checkout@v2
    - name: Install Alpine package build deps
      run: apk add alpine-sdk
    - name: Setup abuild
      run: .github/script/setup-abuild
      env:
        ABUILD_PRIVATE_KEY: ${{secrets.ABUILD_PRIVATE_KEY}}
