name: build

on: [push]

jobs:
  amd64-repo:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.12.0
    steps:
    - name: Install Alpine package build deps
      run: apk add alpine-sdk
